#!/usr/bin/env python3
"""DVG display-list disassembler for the Omega Race vector ROM.

omega.e1/f1 live at 0x9000-0x9fff.  Display-list jump/jsr operands are
12-bit WORD addresses relative to 0x8000, so the vector ROM occupies word
addresses 0x0800-0x0fff.  The ROM is a packed sequence of subroutines
called by JSRL from the RAM display list the game builds at 0x8000.

Output columns: byte addr / word addr / raw words / decoded op.
"""

MEM = bytearray(open("omega_dump.bin", "rb").read())

LO, HI = 0x9000, 0xA000

try:
    from vec_names import VEC_NAMES        # generated by vecxref.py
except ImportError:
    VEC_NAMES = {}


# ---------------------------------------------------------------------------
# cross references: where the MAIN ROM points into the vector ROM.
# Almost nothing JSRLs these shapes from inside the vector ROM itself -
# the game builds display lists in RAM whose JSRL words come from these
# main-ROM data regions, from the object templates, or from computed
# formulas (ship heading, shot aim angle).
# ---------------------------------------------------------------------------

# main-ROM regions holding display-list words, scanned for JSRLs
# 0xC800-0xCFFF (word operands 0x800-0xFFF = this ROM)
REF_REGIONS = [
    (0x01A0, 0x01CB, "POST dlist 01A0"),
    (0x026E, 0x02C6, "POST input dlist 026E"),
    (0x042F, 0x0447, "POST hatch dlist 042F"),
    (0x0447, 0x04E8, "POST grid dlist 0447"),
    (0x30D9, 0x3109, "status tmpl 30D9"),
    (0x3109, 0x3217, "game screen 3109"),
    (0x33D9, 0x33F6, "attract dlist 33D9"),
    (0x3A0E, 0x3A88, "letter wheel 3A0E"),
    (0x3F4D, 0x3F5D, "anim tbl 3F4D"),
    (0x3F5D, 0x3F65, "explosion tbl 3F5D"),
    (0x3F65, 0x3FCD, "hiscore frags 3F65"),
    (0x3FCD, 0x3FF3, "glyph tbl 3FCD"),
]

# 23-byte object templates; shape word at +21/+22 (SHIP holds a table
# pointer and SHOT a placeholder - both fall outside the JSRL range and
# are skipped by the range check)
TEMPLATES = [(0x2F50, "SHIP"), (0x2F67, "DROID"), (0x2F7E, "SHOT"),
             (0x2F95, "COMMAND"), (0x2FAC, "INERT")]

ANIM_IDX = ["droid anim 0", "droid anim 1", "droid anim 2",
            "droid anim 3", "death-ship anim 0", "death-ship anim 1",
            "death-ship anim 2", "death-ship anim 3"]


def build_refs():
    refs = {}

    def add(tgt, txt):
        refs.setdefault(tgt, [])
        if txt not in refs[tgt]:
            refs[tgt].append(txt)

    for lo, hi, label in REF_REGIONS:
        for a in range(lo, hi - 1, 2):
            w = rdwd(a)
            if 0xC800 <= w <= 0xCFFF:
                tgt = 0x8000 + ((w & 0xFFF) << 1)
                if 0x3A2E <= a < 0x3A62:
                    add(tgt, "letter tbl 3A2E '%c'"
                        % chr(ord('A') + (a - 0x3A2E) // 2))
                elif lo == 0x3F4D:
                    add(tgt, "anim tbl 3F4D[%d] = %s (also title shimmer)"
                        % ((a - lo) // 2, ANIM_IDX[(a - lo) // 2]))
                elif lo == 0x3F5D:
                    add(tgt, "explosion anim 3F5D[%d]" % ((a - lo) // 2))
                else:
                    add(tgt, "%s+%02X" % (label, a - lo))
    for base, name in TEMPLATES:
        w = rdwd(base + 21)
        if 0xC800 <= w <= 0xCFFF:
            add(0x8000 + ((w & 0xFFF) << 1),
                "%s template shape word (%04X+21 = %04X)" % (name, base, w))
    # cs_hit_confirm's in-place mutation writes shape word 0xCBAF (0x222A)
    add(0x8000 + ((0xCBAF & 0xFFF) << 1),
        "cs_hit_confirm mutate word CBAF (0x222A)")
    # VG_RESTART_FRAME builds JSRL word 0xCDC2 in place (ld hl,$0DC2 /
    # or $C0 into H at 0x17AB) so no literal CDC2 exists to scan for
    add(0x8000 + ((0xCDC2 & 0xFFF) << 1),
        "VG_RESTART 0x17AB (2P active-score blink, word CDC2 -> 0x81A6)")
    return refs


def family_note(name):
    """Provenance for shapes reached via computed words, by name family."""
    if name.startswith("SHIP_M"):
        return ("hull, heading 0x%02X: X-flip set, SHIP_BASE 30A1[1] = "
                "word $DFC + 30A9 offset" % (0x10 + int(name[6:8])))
    if name.startswith("THRUST_M"):
        return "flame of SHIP_M%s (hull word - 7, ROM 0x1E58)" % name[8:10]
    if name.startswith("SHIP_EXPLODE"):
        return None                       # covered by scanned refs
    if name.startswith("SHIP_"):
        n = int(name[5:7])
        return ("hull, heading 0x%02X: word $800 + 30A9[%d] "
                "(ship shape select 0x1E18)" % (n, n))
    if name.startswith("THRUST_"):
        return "flame of SHIP_%s (hull word - 7, ROM 0x1E58)" % name[7:9]
    if name.startswith("SHOT_"):
        n = int(name[5:7])
        return ("shot/mine at aim angle %d: word $AE7 + 3*%d "
                "(SPAWN_MINE_SHOT 0x2737)" % (n, n))
    if name.startswith("CHAR_"):
        return "text glyph (CHAR_GLYPH_EMIT 0x2C36)"
    if name == "UNUSED_9B84":
        # misnamed: VG_RESTART_FRAME 0x17AB writes its JSRL to dlist
        # 0x81A6 on tick bit 5 (alternating with 0xF000) in 2-player
        # games - the blinking "this score is the active player" mark
        return ("NOT unused: 2P active-player score blink mark; rename "
                "to PLAYER_UP_MARK deferred - the C port's "
                "omega_shapes.h still uses SHAPE_IDX_UNUSED_9B84")
    if name.startswith("UNUSED_"):
        return "unused art - no reference anywhere in either ROM"
    return None


def rdwd(a):
    return MEM[a] | (MEM[a + 1] << 8)


def s12(v):
    return v - 4096 if v & 0x800 else v


def decode(a):
    """returns (nbytes, text, target_byte_addr_or_None, ends_flow)"""
    w1 = rdwd(a)
    op = w1 >> 12
    if op <= 9:
        w2 = rdwd(a + 2)
        y = w1 & 0x3FF
        x = w2 & 0x3FF
        if w1 & 0x400:
            y = -y
        if w2 & 0x400:
            x = -x
        z = w2 >> 12
        return (4, "VCTR  s=%d  dx=%-5d dy=%-5d z=%d" % (op, x, y, z),
                None, False)
    if op == 0xA:
        w2 = rdwd(a + 2)
        return (4, "LABS  scale=%d  x=%-5d y=%-5d" %
                ((w2 >> 12) & 0xF, s12(w2 & 0xFFF), s12(w1 & 0xFFF)),
                None, False)
    if op == 0xB:
        return (2, "HALT", None, True)
    if op == 0xC:
        t = 0x8000 + ((w1 & 0xFFF) << 1)
        return (2, "JSRL  $%04X" % t, t, False)
    if op == 0xD:
        return (2, "RTSL", None, True)
    if op == 0xE:
        t = 0x8000 + ((w1 & 0xFFF) << 1)
        return (2, "JMPL  $%04X" % t, t, True)
    # op == 0xF
    z = (w1 & 0x00F0) >> 4
    y = w1 & 0x300
    x = (w1 & 0x003) << 8
    if w1 & 0x400:
        y = -y
    if w1 & 0x004:
        x = -x
    sc = 2 + ((w1 >> 2) & 0x02) + ((w1 >> 11) & 0x01)
    return (2, "SVEC  s=%d  dx=%-5d dy=%-5d z=%d" % (sc, x, y, z),
            None, False)


def main():
    # pass 1: linear sweep, collect JSRL/JMPL targets as labels
    labels = set()
    a = LO
    while a < HI:
        n, text, tgt, ends = decode(a)
        if tgt is not None and LO <= tgt < HI:
            labels.add(tgt)
        a += n

    # Shapes the glyph tables enter in the MIDDLE of another shape (F,
    # SPACE) have no terminator in front of them, so the sweep above
    # never opens a block for them. vecxref.py knows those entry points;
    # take its name map as the authoritative list of block starts.
    starts = labels | set(VEC_NAMES)

    refs = build_refs()

    # pass 2: emit, starting a new "SUB" block after each RTSL/HALT/JMPL
    out = []
    out.append("; omega.e1/f1 vector ROM 0x9000-0x9fff  (dvgdasm.py)")
    out.append("; word addresses (JSRL operands) are (byte-0x8000)/2")
    out.append(";")
    out.append("; Nothing JSRLs these shapes statically - the game builds")
    out.append("; display lists in RAM. Each block below carries its real")
    out.append("; provenance: 'refs:' = main-ROM data words that point at")
    out.append("; it, or a computed-word formula for the ship/shot")
    out.append("; families.")
    out.append(";")
    out.append("; [THRUST_n][SHIP_n] pairs sit 7 words apart: the entry")
    out.append("; writer takes flame = hull - 7 (ROM 0x1E58). Heading")
    out.append("; bits 4-5 pick a frame set (SHIP_BASE 0x30A1): set 0 =")
    out.append("; SHIP_* (word $800), set 1 = SHIP_M* X-flip (word $DFC),")
    out.append("; sets 2/3 live in vector RAM at 0x8BF8 (180 deg) and")
    out.append("; 0x87F0 (Y-flip) - WALL_BUFFERS_BUILD 0x18BC copies")
    out.append("; 0x9000-0x9407 there and flips SVEC/VCTR sign bits.")
    out.append(";")
    a = LO
    new_block = True
    while a < HI:
        if a == 0x9406:
            out.append("%04X/%03X:  %04X       (orphan word; real shape "
                       "starts at 9408)" % (a, (a - 0x8000) >> 1, rdwd(a)))
            a = 0x9408
            new_block = True
            continue
        n, text, tgt, ends = decode(a)
        if a in starts or new_block:
            wa = (a - 0x8000) >> 1
            tag = VEC_NAMES.get(a, "SUB_%04X" % a)
            out.append("")
            out.append("%s: (JSRL operand $%03X)" % (tag, wa))
            if a in starts and not new_block:
                out.append("; (entered by fall-through: the previous "
                           "shape runs into this one, so a linear sweep "
                           "never sees a block start here)")
            note = family_note(tag)
            if note:
                out.append("; %s" % note)
            for r in refs.get(a, []):
                out.append("; refs: %s" % r)
            if a in labels:
                out.append("; also JSRL'd from within the vector ROM")
            if note is None and a not in refs and a not in labels:
                out.append("; no static reference found")
            new_block = False
        raw = " ".join("%04X" % rdwd(a + i) for i in range(0, n, 2))
        if tgt is not None and LO <= tgt < HI:
            text += "   ; -> " + VEC_NAMES.get(tgt, "SUB_%04X" % tgt)
        out.append("%04X/%03X:  %-10s %s" % (a, (a - 0x8000) >> 1, raw, text))
        if ends:
            new_block = True
        a += n

    with open("omega_vecrom.asm", "w") as f:
        f.write("\n".join(out) + "\n")

    print("labels (JSRL/JMPL targets inside vec ROM): %d" % len(labels))
    # sanity: how many blocks end cleanly
    print("done, wrote omega_vecrom.asm")


if __name__ == "__main__":
    main()
