#!/usr/bin/env python3
"""Generate c_src/omega_dvgprom.c: the DVG state PROM (bitswapped for
Omega Race) and the FULL game-screen wall list.

The walls blob is the complete 0x10E bytes of ROM 0x3109 - including
the eight 0xFFFF placeholder words at +0x84 (dlist 0x8234) and the ten
lives/bonus icon slots - because the port's GAME_DLIST_BUILD patches
the JSRL table from 0x3EE5 over the placeholders at runtime, exactly
like the ROM.
"""

MEM = open("omega_dump.bin", "rb").read()
PROM = open("dvgprom.bin", "rb").read()

WALL_LO, WALL_HI = 0x3109, 0x3109 + 0x10E


def bitswap(x):
    # BITSWAP8(x,7,6,5,4,1,0,3,2): undo Omega Race's swapped output pairs
    return ((x & 0xF0)
            | ((x >> 2) & 0x02) | ((x >> 2) & 0x01)
            | ((x << 2) & 0x08) | ((x << 2) & 0x04))


def rw(a):
    return MEM[a] | (MEM[a + 1] << 8)


out = []
out.append("/* omega_dvgprom.c - generated by disasm/gen_dvgprom.py."
           "  DO NOT EDIT.")
out.append(" *")
out.append(" * omega_dvgprom[]: the DVG state PROM (disasm/dvgprom.bin) "
           "with Omega")
out.append(" * Race's two swapped output pairs undone at generation time "
           "(the same")
out.append(" * BITSWAP8(x,7,6,5,4,1,0,3,2) frametime.cpp applies at "
           "load), so dvg.c")
out.append(" * indexes it as a standard DVG PROM.")
out.append(" *")
out.append(" * omega_walls_words[]: the game-screen wall list, the FULL "
           "0x10E bytes")
out.append(" * of ROM 0x3109, as DVG words. GAME_DLIST_BUILD copies it "
           "to 0x81B0.")
out.append(" * Words +0x84.. (dlist 0x8234-0x8243) are the eight 0xFFFF")
out.append(" * placeholders; drawing them raw is the stray-diagonal bug "
           "- the game")
out.append(" * (and now the port) immediately patches the 0x3EE5 JSRL "
           "table over")
out.append(" * them. The lives/bonus icon slots 0x8258-0x82BA and the "
           "score-line")
out.append(" * digit run at 0x8246 live in this blob too. */")
out.append("")
out.append("const unsigned char omega_dvgprom[0x100] = {")
for i in range(0, 0x100, 12):
    row = [bitswap(b) for b in PROM[i:i + 12]]
    out.append("    " + " ".join("0x%02X," % b for b in row))
out.append("};")
out.append("")
nwords = (WALL_HI - WALL_LO) // 2
out.append("const int omega_walls_word_count = %d;" % nwords)
out.append("const unsigned short omega_walls_words[%d] = {" % nwords)
for a in range(WALL_LO, WALL_HI, 20):
    n = min(10, (WALL_HI - a) // 2)
    out.append("    " + " ".join("0x%04X," % rw(a + j * 2)
                                 for j in range(n)))
out.append("};")

open("../c_src/omega_dvgprom.c", "w").write("\n".join(out) + "\n")
print("wrote c_src/omega_dvgprom.c: prom=256, walls=%d words" % nwords)
