#!/usr/bin/env python3
r"""Generate c_src/omega_postrom.c: the POST / diagnostic screens' display
lists and label text, embedded so the C port builds those screens out of
the REAL ROM bytes instead of a re-encoded copy.

Every screen is a list the ROM copies to vector RAM 0x8000 after
VG_WAIT_WIPE (0x07B6) has filled the region with 0xB000 HALT words, so a
copied list needs no terminator of its own:

  0x01A0  0x2C  test-screen header.  Decodes as
                  8000 LABS y=800 x=416 scale=1
                  8004 VCTR scale-set
                  8008 JMPL ->02C   (jump the marks, into the labels)
                  800A JSRL x4 "  OK"   \ three 4-glyph subroutines,
                  8014 JSRL x4 " NG "    | each ending in the shared
                  801E JSRL x4 "    "   / newline vector at 8026
                  8026 VCTR newline
                  802A RTSL
                so JSRL operand 0x005 = "  OK", 0x00A = " NG ",
                0x00F = blank+newline.
  0x01CC  0xA2  18 label cells of 9 chars, drawn by DRAW_TEXT (0x08C8)
                at 0x802C.  Each cell's trailing '.' encodes JSRL 0x00F,
                so posting a result is a ONE BYTE write over the low
                half of that word: 0x05 pass, 0x0A fail.
  0x026E  0x2C  input-screen header, same shape, marks " LOW" / " HI ".
  0x029A  0x195 45 input label cells of 9 chars.
  0x042F  0x18  cross-hatch page.
  0x0447  0xA0  grid page + the eight-step intensity ramp.

DRAW_TEXT's glyph tables (0x3A2E letters, 0x3FD3 digits) are already
embedded by gen_pagerom.py and are not repeated here.
"""

MEM = open("omega_dump.bin", "rb").read()

BLOBS = [
    ("omega_post_test_hdr",    0x01A0, 0x2C,
     "test-screen header -> 0x8000"),
    ("omega_post_test_text",   0x01CC, 0xA2,
     "18 test label cells, 9 chars each -> DRAW_TEXT at 0x802C"),
    ("omega_post_input_hdr",   0x026E, 0x2C,
     "input-screen header -> 0x8000"),
    ("omega_post_input_text",  0x029A, 0x195,
     "45 input label cells, 9 chars each -> DRAW_TEXT at 0x802C"),
    ("omega_post_xhatch",      0x042F, 0x18,
     "cross-hatch page -> 0x8000"),
    ("omega_post_grid",        0x0447, 0xA0,
     "grid page + intensity ramp -> 0x8000"),
]

out = []
out.append("/* omega_postrom.c - generated by disasm/gen_postrom.py."
           "  DO NOT EDIT. */")
out.append("#include <stdint.h>")
out.append("")
for name, lo, n, note in BLOBS:
    out.append("/* ROM 0x%04X-0x%04X: %s */" % (lo, lo + n - 1, note))
    out.append("const uint8_t %s[0x%X] = {" % (name, n))
    for a in range(lo, lo + n, 16):
        row = MEM[a:min(a + 16, lo + n)]
        out.append("    " + "".join("0x%02X," % b for b in row) +
                   "  /* %04X */" % a)
    out.append("};")
    out.append("")

open("../c_src/omega_postrom.c", "w", newline="\r\n").write("\n".join(out))
print("wrote c_src/omega_postrom.c  (%d blobs, %d bytes)"
      % (len(BLOBS), sum(n for _, _, n, _ in BLOBS)))
