#!/usr/bin/env python3
r"""Generate c_src/omega_sndrom.c: the sound board's DATA region, embedded
so the C port's sound engine runs the REAL ROM bytes instead of a
re-encoded copy.

`sound_k5.bin` is the 2 KB sound-board ROM (0x0000-0x07FF). Everything
below 0x024A is Z80 code (see `omega_sound.asm`, already ported by hand
to the sound engine in c_src). Everything from 0x024A on is DATA the
interpreter only ever reads, never executes:

  0x024A  0x5B6  the command dispatch table (23 {script_ptr, var_ptr}
                 pairs for commands 0x00-0x16, see SOUND_NOTES.md) plus
                 every sound script it points into, packed end to end
                 out to the end of the ROM at 0x07FF.

That single span is dumped verbatim here so the port's script
interpreter walks the identical bytes the real AY-3-8910 driver did.
"""

MEM = open("sound_k5.bin", "rb").read()

LO = 0x024A
HI = 0x0800
SIZE = HI - LO  # 0x05B6

out = []
out.append("/* omega_sndrom.c - generated by disasm/gen_sndrom.py.  DO NOT EDIT. */")
out.append("#include <stdint.h>")
out.append("")
out.append("/* ROM 0x%04X-0x%04X: sound command dispatch table + scripts "
           "(sound_k5.bin) */" % (LO, HI - 1))
out.append("const uint8_t omega_sndrom[0x%X] = {" % SIZE)
for a in range(LO, HI, 16):
    row = MEM[a:min(a + 16, HI)]
    out.append("    " + "".join("0x%02X," % b for b in row) +
               "  /* %04X */" % a)
out.append("};")
out.append("")

open("../c_src/omega_sndrom.c", "w", newline="\r\n").write("\n".join(out))
print("wrote c_src/omega_sndrom.c  (0x%X bytes, ROM 0x%04X-0x%04X)"
      % (SIZE, LO, HI - 1))
