#!/usr/bin/env python3
"""Generate c_src/omega_pagerom.c: the main ROM's page-script region and
glyph tables, embedded so the C port's DVG page renderer interprets the
REAL page bytes (headers, glyphs, escapes) instead of a re-encoded copy.

Contents:
  omega_page_rom[]   ROM 0x3217-0x3EE4: every page script, the attract
                     dlist fragment (0x33D9 fill word + 0x33DB border),
                     and the letter-wheel alphabet blob 0x3A0E (whose
                     0x3A2E table doubles as DRAW_TEXT's A-Z JSRLs).
  omega_page_table[] ROM 0x3F15: page pointer table (pages 1..0x1C).
  omega_glyph_rom[]  ROM 0x3FCD-0x3FF2: digit/char glyph JSRL words
                     (0x3FCF '.', 0x3FD1 ',', 0x3FD3 base for '/'..'>',
                     0x3FD5 digit base, index 0x0A/' ' = blank).
"""

MEM = open("omega_dump.bin", "rb").read()

PAGE_LO, PAGE_HI = 0x3217, 0x3FCD
TBL, TBL_N = 0x3F15, 0x1C
GLY_LO, GLY_HI = 0x3FCD, 0x3FF7    # includes 3FF3/3FF5: the droid-icon
                                   # glyphs chars '?'/'@' index (they sit
                                   # past the "digit" run, before the BCD
                                   # +1 constant at 3FF7)


def rw(a):
    return MEM[a] | (MEM[a + 1] << 8)


out = []
out.append("/* omega_pagerom.c - generated by disasm/gen_pagerom.py."
           "  DO NOT EDIT. */")
out.append("#include <stdint.h>")
out.append("")
out.append("/* ROM 0x%04X-0x%04X: page scripts + attract fragment + "
           "alphabet blob */" % (PAGE_LO, PAGE_HI - 1))
out.append("const uint8_t omega_page_rom[0x%X] = {" % (PAGE_HI - PAGE_LO))
for a in range(PAGE_LO, PAGE_HI, 16):
    row = MEM[a:min(a + 16, PAGE_HI)]
    out.append("    " + "".join("0x%02X," % b for b in row) +
               "  /* %04X */" % a)
out.append("};")
out.append("")
out.append("/* ROM 0x3F15: page pointer table, pages 1..0x1C */")
out.append("const uint16_t omega_page_table[0x%X] = {" % TBL_N)
for i in range(0, TBL_N, 8):
    out.append("    " + " ".join("0x%04X," % rw(TBL + (i + j) * 2)
                                 for j in range(min(8, TBL_N - i))))
out.append("};")
out.append("")
out.append("/* ROM 0x3FCD-0x3FF2: glyph JSRL words (see gen header) */")
out.append("const uint16_t omega_glyph_rom[%d] = {" % ((GLY_HI - GLY_LO) // 2))
for a in range(GLY_LO, GLY_HI, 16):
    n = min(8, (GLY_HI - a) // 2)
    out.append("    " + " ".join("0x%04X," % rw(a + j * 2)
                                 for j in range(n)))
out.append("};")

open("../c_src/omega_pagerom.c", "w").write("\n".join(out) + "\n")
print("wrote c_src/omega_pagerom.c: rom=%d bytes, table=%d, glyphs=%d"
      % (PAGE_HI - PAGE_LO, TBL_N, (GLY_HI - GLY_LO) // 2))
