/* omega_shapes.h - generated by vecxref.py
 * All 0x9000-0x9FFF vector-ROM shapes as line segments, plus the
 * playfield WALLS fragment (ROM 0x3109, absolute coordinates).
 * Units: DVG units at global scale 0 (y up); callers scaled these via
 * LABS scale, so multiply as needed. z = DVG intensity 1..15.
 * adv_x/adv_y = net beam displacement of the shape (the real glyph
 * advance for text layout).
 */
#ifndef OMEGA_SHAPES_H
#define OMEGA_SHAPES_H

typedef struct { float x0, y0, x1, y1; unsigned char z; } vec_seg;
typedef struct {
    const char*   name;
    unsigned short rom_addr;   /* byte address 0x9000.. */
    unsigned short word_addr;  /* JSRL operand */
    int            nsegs;
    const vec_seg* segs;
    float          adv_x, adv_y;
} vec_shape;

extern const vec_shape omega_shapes[];
extern const int omega_shape_count;
extern const short omega_char_shape[128];  /* ASCII -> shape index, -1 = none */

#define SHAPE_IDX_THRUST_00        0
#define SHAPE_IDX_SHIP_00          1
#define SHAPE_IDX_THRUST_01        2
#define SHAPE_IDX_SHIP_01          3
#define SHAPE_IDX_THRUST_02        4
#define SHAPE_IDX_SHIP_02          5
#define SHAPE_IDX_THRUST_03        6
#define SHAPE_IDX_SHIP_03          7
#define SHAPE_IDX_THRUST_04        8
#define SHAPE_IDX_SHIP_04          9
#define SHAPE_IDX_THRUST_05        10
#define SHAPE_IDX_SHIP_05          11
#define SHAPE_IDX_THRUST_06        12
#define SHAPE_IDX_SHIP_06          13
#define SHAPE_IDX_THRUST_07        14
#define SHAPE_IDX_SHIP_07          15
#define SHAPE_IDX_THRUST_08        16
#define SHAPE_IDX_SHIP_08          17
#define SHAPE_IDX_THRUST_09        18
#define SHAPE_IDX_SHIP_09          19
#define SHAPE_IDX_THRUST_10        20
#define SHAPE_IDX_SHIP_10          21
#define SHAPE_IDX_THRUST_11        22
#define SHAPE_IDX_SHIP_11          23
#define SHAPE_IDX_THRUST_12        24
#define SHAPE_IDX_SHIP_12          25
#define SHAPE_IDX_THRUST_13        26
#define SHAPE_IDX_SHIP_13          27
#define SHAPE_IDX_THRUST_14        28
#define SHAPE_IDX_SHIP_14          29
#define SHAPE_IDX_THRUST_15        30
#define SHAPE_IDX_SHIP_15          31
#define SHAPE_IDX_CMDSHIP_00       32
#define SHAPE_IDX_DROID_00         33
#define SHAPE_IDX_DROID_01         34
#define SHAPE_IDX_DROID_02         35
#define SHAPE_IDX_DEATH_SHIP_00    36
#define SHAPE_IDX_DEATH_SHIP_01    37
#define SHAPE_IDX_DEATH_SHIP_02    38
#define SHAPE_IDX_DEATH_SHIP_03    39
#define SHAPE_IDX_SHOT_00          40
#define SHAPE_IDX_SHOT_01          41
#define SHAPE_IDX_SHOT_02          42
#define SHAPE_IDX_SHOT_03          43
#define SHAPE_IDX_SHOT_04          44
#define SHAPE_IDX_SHOT_05          45
#define SHAPE_IDX_SHOT_06          46
#define SHAPE_IDX_SHOT_07          47
#define SHAPE_IDX_SHOT_08          48
#define SHAPE_IDX_SHOT_09          49
#define SHAPE_IDX_SHOT_10          50
#define SHAPE_IDX_SHOT_11          51
#define SHAPE_IDX_SHOT_12          52
#define SHAPE_IDX_SHOT_13          53
#define SHAPE_IDX_SHOT_14          54
#define SHAPE_IDX_SHOT_15          55
#define SHAPE_IDX_SHOT_16          56
#define SHAPE_IDX_SHOT_17          57
#define SHAPE_IDX_SHOT_18          58
#define SHAPE_IDX_SHOT_19          59
#define SHAPE_IDX_SHOT_20          60
#define SHAPE_IDX_SHOT_21          61
#define SHAPE_IDX_SHOT_22          62
#define SHAPE_IDX_SHOT_23          63
#define SHAPE_IDX_SHOT_24          64
#define SHAPE_IDX_SHOT_25          65
#define SHAPE_IDX_SHOT_26          66
#define SHAPE_IDX_SHOT_27          67
#define SHAPE_IDX_SHOT_28          68
#define SHAPE_IDX_SHOT_29          69
#define SHAPE_IDX_SHOT_30          70
#define SHAPE_IDX_SHOT_31          71
#define SHAPE_IDX_SHOT_32          72
#define SHAPE_IDX_SHOT_33          73
#define SHAPE_IDX_SHOT_34          74
#define SHAPE_IDX_SHOT_35          75
#define SHAPE_IDX_SHOT_36          76
#define SHAPE_IDX_SHOT_37          77
#define SHAPE_IDX_SHOT_38          78
#define SHAPE_IDX_SHOT_39          79
#define SHAPE_IDX_SHOT_40          80
#define SHAPE_IDX_SHOT_41          81
#define SHAPE_IDX_SHOT_42          82
#define SHAPE_IDX_SHOT_43          83
#define SHAPE_IDX_SHOT_44          84
#define SHAPE_IDX_SHOT_45          85
#define SHAPE_IDX_SHOT_46          86
#define SHAPE_IDX_SHOT_47          87
#define SHAPE_IDX_SHOT_48          88
#define SHAPE_IDX_SHOT_49          89
#define SHAPE_IDX_SHOT_50          90
#define SHAPE_IDX_SHOT_51          91
#define SHAPE_IDX_SHOT_52          92
#define SHAPE_IDX_SHOT_53          93
#define SHAPE_IDX_SHOT_54          94
#define SHAPE_IDX_SHOT_55          95
#define SHAPE_IDX_SHOT_56          96
#define SHAPE_IDX_SHOT_57          97
#define SHAPE_IDX_SHOT_58          98
#define SHAPE_IDX_SHOT_59          99
#define SHAPE_IDX_SHOT_60          100
#define SHAPE_IDX_SHOT_61          101
#define SHAPE_IDX_SHOT_62          102
#define SHAPE_IDX_SHOT_63          103
#define SHAPE_IDX_PHOTON_MINE      104
#define SHAPE_IDX_VAPOR_MINE       105
#define SHAPE_IDX_SHIP_EXPLODE_00  106
#define SHAPE_IDX_SHIP_EXPLODE_01  107
#define SHAPE_IDX_SHIP_EXPLODE_02  108
#define SHAPE_IDX_CHAR_A           109
#define SHAPE_IDX_CHAR_B           110
#define SHAPE_IDX_CHAR_C           111
#define SHAPE_IDX_CHAR_D           112
#define SHAPE_IDX_CHAR_E           113
#define SHAPE_IDX_CHAR_F           114
#define SHAPE_IDX_CHAR_G           115
#define SHAPE_IDX_CHAR_H           116
#define SHAPE_IDX_CHAR_I           117
#define SHAPE_IDX_CHAR_J           118
#define SHAPE_IDX_CHAR_K           119
#define SHAPE_IDX_CHAR_L           120
#define SHAPE_IDX_CHAR_M           121
#define SHAPE_IDX_CHAR_N           122
#define SHAPE_IDX_CHAR_O           123
#define SHAPE_IDX_CHAR_P           124
#define SHAPE_IDX_CHAR_Q           125
#define SHAPE_IDX_CHAR_R           126
#define SHAPE_IDX_CHAR_S           127
#define SHAPE_IDX_CHAR_T           128
#define SHAPE_IDX_CHAR_U           129
#define SHAPE_IDX_CHAR_V           130
#define SHAPE_IDX_CHAR_W           131
#define SHAPE_IDX_CHAR_X           132
#define SHAPE_IDX_CHAR_Y           133
#define SHAPE_IDX_CHAR_Z           134
#define SHAPE_IDX_CHAR_0           135
#define SHAPE_IDX_CHAR_1           136
#define SHAPE_IDX_CHAR_2           137
#define SHAPE_IDX_CHAR_3           138
#define SHAPE_IDX_CHAR_4           139
#define SHAPE_IDX_CHAR_5           140
#define SHAPE_IDX_CHAR_6           141
#define SHAPE_IDX_CHAR_7           142
#define SHAPE_IDX_CHAR_SPACE       143
#define SHAPE_IDX_CHAR_8           144
#define SHAPE_IDX_CHAR_9           145
#define SHAPE_IDX_CHAR_PERIOD      146
#define SHAPE_IDX_CHAR_COMMA       147
#define SHAPE_IDX_CHAR_SPACE2      148
#define SHAPE_IDX_UNUSED_9B84      149
#define SHAPE_IDX_CHAR_x3D         150
#define SHAPE_IDX_CHAR_x2F         151
#define SHAPE_IDX_UNUSED_9BAE      152
#define SHAPE_IDX_SHIP_M00         153
#define SHAPE_IDX_THRUST_M00       154
#define SHAPE_IDX_SHIP_M01         155
#define SHAPE_IDX_THRUST_M01       156
#define SHAPE_IDX_SHIP_M02         157
#define SHAPE_IDX_THRUST_M02       158
#define SHAPE_IDX_SHIP_M03         159
#define SHAPE_IDX_THRUST_M03       160
#define SHAPE_IDX_SHIP_M04         161
#define SHAPE_IDX_THRUST_M04       162
#define SHAPE_IDX_SHIP_M05         163
#define SHAPE_IDX_THRUST_M05       164
#define SHAPE_IDX_SHIP_M06         165
#define SHAPE_IDX_THRUST_M06       166
#define SHAPE_IDX_SHIP_M07         167
#define SHAPE_IDX_THRUST_M07       168
#define SHAPE_IDX_SHIP_M08         169
#define SHAPE_IDX_THRUST_M08       170
#define SHAPE_IDX_SHIP_M09         171
#define SHAPE_IDX_THRUST_M09       172
#define SHAPE_IDX_SHIP_M10         173
#define SHAPE_IDX_THRUST_M10       174
#define SHAPE_IDX_SHIP_M11         175
#define SHAPE_IDX_THRUST_M11       176
#define SHAPE_IDX_SHIP_M12         177
#define SHAPE_IDX_THRUST_M12       178
#define SHAPE_IDX_SHIP_M13         179
#define SHAPE_IDX_THRUST_M13       180
#define SHAPE_IDX_SHIP_M14         181
#define SHAPE_IDX_THRUST_M14       182
#define SHAPE_IDX_SHIP_M15         183
#define SHAPE_IDX_THRUST_M15       184
#define SHAPE_IDX_WALLS            185

#endif
