/* post.c - Omega Race C conversion: power-on self test / diagnostic screens.
 *
 * Translates disasm/omega_main.asm 0x04E8-0x0940 (POST_START, POST_CYCLE,
 * POST_TESTSW_GATE, the 14 test stages, POST_SHOW_BITS, the cross-hatch /
 * grid / sound screens) - the branch the ROM takes when the test switch is
 * held at boot. See disasm/BOOT_AND_IRQ_NOTES.md for the walkthrough.
 *
 * ---- how the ROM draws these screens ---------------------------------
 * Each screen starts with a 0x2C-byte header copied to vector RAM 0x8000,
 * then DRAW_TEXT appends one JSRL per label character starting at 0x802C.
 * The copy happens right after VG_WAIT_WIPE (0x07B6) has filled the whole
 * region with 0xB000 HALT words, which is why no blob carries a
 * terminator of its own.
 *
 * This port does the same thing with the same bytes: the ROM blobs live
 * in omega_postrom.c (generated by disasm/gen_postrom.py) and the
 * builders are dvg_post_* in dvg_pages.c. Nothing in this file computes
 * geometry or picks glyphs - it decides WHAT to post, and the
 * display list decides where it lands.
 *
 * Decoding the header (0x01A0) shows why the result marks work the way the
 * notes describe:
 *
 *   8000  LABS y=800 x=416 scale=1
 *   8004  VCTR scale 8, zero          (the scale-setting idiom)
 *   8008  JMPL ->02C                  jump over the marks, into the labels
 *   800A  JSRL SPACE SPACE 'O' 'K'    \
 *   8012  JMPL ->026                   |  three 4-glyph SUBROUTINES,
 *   8014  JSRL SPACE 'N' 'G' SPACE     |  each ending in a shared
 *   801C  JMPL ->026                   |  newline vector
 *   801E  JSRL SPACE x4               /
 *   8026  VCTR scale 7 dy=-79 dx=-767  carriage return + line feed
 *   802A  RTSL
 *
 * So JSRL operand 0x005 draws "  OK", 0x00A draws " NG ", 0x00F draws four
 * spaces - and every label's trailing '.' is DRAW_TEXT's encoding for JSRL
 * 0x00F (see CHAR_GLYPH_EMIT's table at 0x3FCF). The '.' IS the blank mark
 * plus the newline. Writing a result is one word: 0x05 pass, 0x0A fail,
 * exactly as BOOT_AND_IRQ_NOTES.md says, stepping DE by 0x12 (one 9-glyph
 * cell) per test.
 *
 * The input screen (header 0x026E) is the same shape with its own marks -
 * 0x005 = " LOW", 0x00A = " HI " - so POST_SHOW_BITS reuses the same two
 * offsets to render a live bit as a row.
 *
 * Geometry below is read straight off those words using dvg.c's scale
 * arithmetic (delta = v * 2^(temp+1) / 1024, temp = LABS scale + VCTR
 * opcode), so the rows land where the hardware puts them:
 *   test screen : x=416 y=800, scale 1 -> glyph pitch 32, row pitch 39.5
 *   input screen: x=416 y=900, scale 0 -> glyph pitch 16, row pitch 15.75
 *
 * ---- what the tests actually test ------------------------------------
 * The ROM's 14 stages checksum the four program ROMs, pattern-test main
 * RAM / NVRAM / vector RAM, and checksum the two vector ROMs. In this port
 * there is no Z80 address space: program state is a C struct and the vector
 * data is a generated table. Those stages therefore have nothing to read,
 * and are reported OK - the screen is faithful, the marks are vestigial.
 * The two that CAN be checked for real are checked for real:
 *   BBU RAM  - the NVRAM image the host restored, validated exactly as
 *              GAME_INIT does (nibble template + BCD ranges)
 *   V ROM 1/2 - the generated vector-ROM table, summed against its own
 *              length so a truncated or swapped omega_vecrom.c shows NG
 * Each row below says which kind it is. Nothing here invents a failure
 * mode the port cannot actually have.
 */
#include <stdint.h>
#include <string.h>
#include "omega_state.h"
#include "omega_shapes.h"

/* ---- cross-module externs -------------------------------------------- */
extern void game_init(void);                /* GAME_INIT 0x0955 (mainline.c) */
extern void omega_hw_sound(uint8_t cmd);    /* sound_samples.c               */
extern void dvg_post_tests_page(void);      /* dvg_pages.c: 0x04F5   */
extern void dvg_post_inputs_page(void);     /*              0x06B0   */
extern void dvg_post_xhatch_page(void);     /*              0x073D   */
extern void dvg_post_grid_page(void);       /*              0x075F   */
extern void dvg_post_sound_page(void);      /*              0x0786   */
extern void dvg_post_mark(int cell, uint8_t op);   /*       0x0813   */
extern void dvg_dlist_reset(void);          /* dvg.c: VG_WAIT_WIPE   */

extern const unsigned char omega_vecrom[0x1000];  /* omega_vecrom.c: the
                                       * omega.e1 + omega.f1 image, two 2K
                                       * halves = the ROM's V ROM 1 / 2   */
#define VECROM_LEN 0x1000

void post_boot(void);
void post_enter(void);
int  post_frame(void);

/* ---- the ROM screens, and where a result goes ------------------------
 * The screens are built by dvg_pages.c (dvg_post_*) out of the ROM blobs
 * in omega_postrom.c, so no geometry, label text or glyph work happens
 * here - the header carries the position and scale, and the
 * label bytes are the machine's own.
 *
 * A result is one BYTE written over the low half of a label cell's
 * trailing '.' word (JSRL 0x00F, blank + newline): 0x05 selects the
 * "  OK" subroutine, 0x0A selects " NG ". Cells are 9 words apart.
 */
#define MARK_OK  0x05             /* csum_result_mark 0x0811          */
#define MARK_NG  0x0A             /* csum_result_mark 0x080D          */

enum { POST_TESTS = 0, POST_INPUTS, POST_XHATCH, POST_GRID, POST_SOUND };

/* ---- the 14 test stages ----------------------------------------------
 * The ROM runs 14 stages against an 18-cell label list. Before each new
 * group it does an extra `de += 0x12` (0x059B, 0x05E8, 0x0605, 0x0670)
 * to step over that group's blank spacer cell, which is why the stage
 * index and the cell index diverge. Cells, in ROM order:
 *
 *   0 P ROM 1   1 P ROM 2   2 P ROM 3   3 P ROM 4   [4 spacer]
 *   5 P RAM 1   6 P RAM 2   7 P RAM 3               [8 spacer]
 *   9 BBU RAM                                       [10 spacer]
 *  11 V RAM 1  12 V RAM 2  13 V RAM 3  14 V RAM 4   [15 spacer]
 *  16 V ROM 1  17 V ROM 2
 */
#define POST_STAGES 14
static const uint8_t TEST_CELL[POST_STAGES] = {
    0, 1, 2, 3,   5, 6, 7,   9,   11, 12, 13, 14,   16, 17
};

/* kind: 0 = vestigial (no Z80 memory in this port - see the file header),
 * 1 = the persisted NVRAM image, 2 = the generated vector-ROM table. */
static const uint8_t TEST_KIND[POST_STAGES] = {
    0, 0, 0, 0,   0, 0, 0,   1,   0, 0, 0, 0,    2, 2
};

/* ---- the two real checks --------------------------------------------- */

/* BBU RAM: the NVRAM image, validated the way GAME_INIT does at
 * 0x09B4-0x0A13 - the 2x16 nibble template plus BCD ranges. */
static int nvram_image_ok(void)
{
    static const uint8_t REF[16] = {
        0x0F, 0x0D, 0x0B, 0x09, 0x07, 0x05, 0x03, 0x01,
        0x00, 0x02, 0x04, 0x06, 0x08, 0x0A, 0x0C, 0x0E,
    };
    int i;
    for (i = 0; i < 16; i++) {
        if ((g.nvram_template[i] & 0x0F) != REF[i]) return 0;
        if ((g.nvram_template[16 + i] & 0x0F) != REF[i]) return 0;
    }
    for (i = 0; i < 0x40; i++) {
        uint8_t v = g.bookkeep[i];
        if ((v & 0x0F) > 9 || ((v >> 4) & 0x0F) > 9) return 0;
    }
    if ((g.nvram_credits[0] & 0x0F) > 9 || (g.nvram_credits[1] & 0x0F) > 9) return 0;
    return 1;
}

/* V ROM 1/2: the ROM checksums each 2K half of the vector ROM. The port
 * carries that data as a generated table, so check the table is present
 * and the requested half is fully populated - a truncated or swapped
 * omega_vecrom.c is the failure this can actually catch. */
static int vecrom_half_ok(int half)
{
    int lo = half * 0x800, hi = lo + 0x800;
    int i, nonzero = 0;
    if (VECROM_LEN < hi) return 0;
    for (i = lo; i < hi; i++) if (omega_vecrom[i]) nonzero++;
    return nonzero > 0;
}

static int test_passes(int idx)
{
    switch (TEST_KIND[idx]) {
    case 1:  return nvram_image_ok();
    case 2:  return vecrom_half_ok(idx == 12 ? 0 : 1);   /* V ROM 1 / 2 */
    default: return 1;      /* no Z80 memory in this port - see header */
    }
}

/* ---- drawing: build the ROM list, then post marks into it ------------- */

/* post_draw_header 0x04F5 plus the stages' own result writes. Stages that
 * have not run yet keep the label's blank mark, so the marks appear in
 * sequence exactly as they do on hardware. */
static void draw_test_screen(void)
{
    int i;
    dvg_post_tests_page();
    for (i = 0; i < POST_STAGES && i < g.post_step; i++)
        dvg_post_mark(TEST_CELL[i], test_passes(i) ? MARK_OK : MARK_NG);
}

/* POST_SHOW_BITS 0x08A0. `rrc c` puts bit 0 in carry first, and carry set
 * writes 0x0A - so a HIGH bit reads " HI " and a low one " LOW". The
 * trailing cell step is the ROM's extra `de += 0x12` at 0x08BA, which is
 * what leaves a blank row between groups. */
static void post_show_bits(uint8_t v, int n, int* cell)
{
    int i;
    for (i = 0; i < n; i++) {
        dvg_post_mark((*cell)++, (v & 1) ? MARK_NG : MARK_OK);
        v = (uint8_t)((v >> 1) | (v << 7));            /* rrc */
    }
    (*cell)++;
}

/* post_input_loop 0x06CE-0x072A: six groups, each masked and packed by the
 * ROM before POST_SHOW_BITS walks it. The masks are the ROM's own. */
static void draw_input_screen(void)
{
    uint8_t p1 = omega_hw_in_p1();
    uint8_t p2 = omega_hw_in_p2();
    int cell = 0;

    dvg_post_inputs_page();
    /* 0x06D1: (p1 & 03) | ((p1 & F0) >> 2) - coin 1/2, tilt, thrust,
     * fire, test switch */
    post_show_bits((uint8_t)((p1 & 0x03) | ((p1 & 0xF0) >> 2)), 6, &cell);
    /* 0x06E6: (p2 & 0F) | ((p2 & C0) >> 2) */
    post_show_bits((uint8_t)((p2 & 0x0F) | ((p2 & 0xC0) >> 2)), 6, &cell);
    /* 0x06FB: spinner 1, rotated right twice then masked to 6 bits */
    post_show_bits((uint8_t)((omega_hw_spinner() >> 2) & 0x3F), 6, &cell);
    /* 0x070A: spinner 2, masked only */
    post_show_bits((uint8_t)(omega_hw_spinner2() & 0x3F), 6, &cell);
    post_show_bits(omega_hw_dsw_c4(), 8, &cell);        /* 0x0717 */
    post_show_bits(omega_hw_dsw_c6(), 8, &cell);        /* 0x0722 */
}
/* ---- the state machine ------------------------------------------------ */

/* EDGE_BIT6_IX 0x07DD: advance on the falling edge of fire (port 0x11
 * bit 6, active low). */
static int fire_edge(void)
{
    uint8_t now = (uint8_t)((omega_hw_in_p1() & 0x40) ? 0 : 1);
    int edge = (now && !g.post_fire_prev);
    g.post_fire_prev = now;
    return edge;
}

static int test_switch_held(void)
{
    return (omega_hw_in_p1() & 0x80) == 0;    /* active low */
}

/* POST_START 0x04E8 / POST_TESTSW_GATE 0x050A. The host calls this once at
 * boot instead of going straight to game_init(): switch released takes the
 * ROM's `jp GAME_INIT`, switch held enters the self test. */
void post_boot(void)
{
    omega_hw_sound(0);                        /* ROM 0x04E8-0x04EA */
    if (!test_switch_held()) {
        game_init();
        return;
    }
    /* The ROM's BBU RAM stage reads the physical NVRAM chip, and POST runs
     * BEFORE GAME_INIT - so pull the persisted image in here rather than
     * testing the blank struct GAME_INIT has not filled yet. Harmless to
     * do twice: nvram_boot_load() loads it again on the way out. A machine
     * whose NVRAM has never been written really does fail this, and
     * GAME_INIT then wipes and reinitialises it, exactly as on hardware. */
    omega_hw_nvram_load();
    post_enter();
}

/* HOST AFFORDANCE, not ROM behaviour. On hardware the diagnostics are
 * power-on only: POST_TESTSW_GATE reads the switch once, at 0x050A, and
 * nothing re-enters it. That is a poor fit for a window that takes
 * keyboard focus asynchronously, so the host also binds F2 to "enter the
 * diagnostics now" from any state - attract, the credit screen, or a game
 * in progress.
 *
 * Leaving still goes out through GAME_INIT, the ROM's own and only exit
 * from POST, so entering from a game in progress ends that game exactly
 * as an operator power-cycling the cabinet would. */
void post_enter(void)
{
    omega_hw_nvram_load();       /* the BBU RAM stage reads the chip */
    g.post_active    = 1;
    g.post_stage     = POST_TESTS;
    g.post_step      = 0;
    g.post_ticks     = 0;
    g.post_fire_prev = 0;
}

/* One frame of POST. Returns 1 while POST owns the screen, 0 once it has
 * handed off to the game (the ROM loops the whole cycle while the switch
 * is held, so this only returns 0 after the switch is released). */
int post_frame(void)
{
    if (!g.post_active) return 0;

    /* Each screen builder does the ROM's own VG_WAIT_WIPE (0x07B6) fill
     * before copying its list, so there is no separate reset here. */

    switch (g.post_stage) {
    case POST_TESTS:
        /* One stage per ~8 frames, so the marks appear in sequence the way
         * they do on hardware as each test completes. */
        draw_test_screen();
        g.post_ticks = (int16_t)(g.post_ticks - (int16_t)g.tick_delta);
        if (g.post_ticks <= 0) {
            g.post_ticks = (int16_t)(g.post_ticks + 32);
            if (g.post_step < POST_STAGES) g.post_step++;
        }
        if (g.post_step >= POST_STAGES && fire_edge()) {
            g.post_stage = POST_INPUTS;
        }
        break;

    case POST_INPUTS:
        draw_input_screen();
        if (fire_edge()) g.post_stage = POST_XHATCH;
        break;

    case POST_XHATCH:
        dvg_post_xhatch_page();
        if (fire_edge()) g.post_stage = POST_GRID;
        break;

    case POST_GRID:
        dvg_post_grid_page();
        if (fire_edge()) {
            g.post_stage = POST_SOUND;
            omega_hw_sound(0x16);             /* ROM 0x0781-0x0783 */
        }
        break;

    case POST_SOUND:
        /* post_sound_loop 0x0786 calls VG_WAIT_WIPE every pass and never
         * VG_KICK_IY, so the generator is never restarted: this screen is
         * blank on hardware. */
        dvg_post_sound_page();
        if (fire_edge()) {
            omega_hw_sound(0);                /* ROM 0x0799-0x079B */
            /* ROM 0x0797: jp POST_CYCLE - the whole self test repeats
             * while the switch is held; releasing it leaves for the game. */
            if (test_switch_held()) {
                g.post_stage = POST_TESTS;
                g.post_step  = 0;
                g.post_ticks = 0;
            } else {
                g.post_active = 0;
                dvg_dlist_reset();
                game_init();
                return 0;
            }
        }
        break;

    default:
        g.post_active = 0;
        return 0;
    }
    return 1;
}
