/* sound_board.c - Omega Race C port: the sound board, synthesized.
 *
 * The Windows backend's default sound path ([sound] ay8910=1; 0 selects
 * sound_samples.c's sample map instead): a 1:1 translation of the sound Z80's whole program,
 * sound_k5.bin 0x0000-0x0249 (disasm/omega_sound.asm), driving two
 * AY-3-8912s (ay8910.c).  That program is a bytecode interpreter: a
 * command latched from the main CPU's port 0x14 starts one of 23 scripts;
 * every 244 Hz NMI each live script runs until its next delay, editing a
 * 32-byte shadow of the two chips' registers, and the pass ends by
 * flushing the shadow bytes that changed to the chips.
 *
 * What is kept exactly
 *  - The board's memory map.  The scripts and the command table are the
 *    ROM's own bytes (omega_sndrom.c, ROM 0x024A-0x07FF, generated by
 *    disasm/gen_sndrom.py) and they carry absolute pointers into both ROM
 *    and RAM, so RAM is modelled as the board's 1 KB at 0x1000-0x13FF and
 *    every access goes through rd()/wr() at its real address.  Nothing is
 *    re-laid-out, so nothing can be laid out wrong.
 *  - Unmapped reads return 0xFF.  Script 00 has no FF terminator: its last
 *    op's operand is at 0x0800, one past the ROM, and the byte after that
 *    ends the script only because the open bus reads high (SOUND_NOTES.md,
 *    "command 0x00 runs off the end of the ROM").
 *  - One function per named routine, per CONVENTIONS.md rule 1.
 *
 * What is different, and why it does not matter
 *  - The Z80 took the command IRQ wherever it happened to be.  Here a
 *    command always lands between two ticks, which is where the Z80 was
 *    all but a sliver of the time: spinning in snd_main_loop on snd_tick.
 *    The one thing that depends on it is SND_IRQ_LATCH's `cp (iy+3)`
 *    dedup, which can only match while SCRIPT_RUN has snd_cur_cmd set to
 *    the running slot; between ticks that byte is 0x18 and no command
 *    (all < 0x17) matches.  The compare is translated anyway.
 *  - A pass here takes no time. On the board the 1.5 MHz Z80 needs ~3900
 *    cycles of the tick's 6144 for an idle pass, and the heavy ones LOSE
 *    ticks: SND_RESET's RAM clear alone is ~3.5 ticks, and a pass running
 *    script 00's full register wipe spans two or three NMIs - snd_tick
 *    moving by more than one still buys one pass. So after a command 0,
 *    0x13 or 0x14 (and 0x01's tail) the real board's scripts sit 2-5
 *    ticks (8-20 ms) behind where this port has them, which can shift how
 *    a LATER command interleaves with a sound already running by a pass
 *    or two. (This is what SOUND_CMD_SEND's 4 x WAIT_NEXT_TICK after a
 *    command 0 is for: it sits out the reset.) Measured by the oracle -
 *    see probe_sndboard's tick-skew report; every single-command stream
 *    is write-for-write identical, and in the mixed scenarios every
 *    register still receives the identical value sequence. Closing this
 *    would take a T-state cost model of the interpreter; not done.
 *  - Dropped hardware artifacts (rule 6): the NMI's stack-page sanity
 *    check (0x0068-0x006F hangs if SP has left page 0x13), the di/ei
 *    windows in SCRIPT_RUN (there is no concurrent IRQ to fence off), and
 *    the register file (exx / ex af,af').
 *
 * The clocks (MAME 0.286 omegrace.cpp, and sheet omegaD for the NMI):
 * both AYs run at 12 MHz / 12 = 1 MHz and mix equally to mono; the NMI is
 * the main board's own GBNMI, 12 MHz / 16 / 256 / 12 = 244.140625 Hz - the
 * same net that clocks omega_irq_244hz, so the host runs sndboard_tick()
 * once per main tick.
 *
 * State: the sound board is a second machine with its own RAM, so its
 * state is this file's statics, not `omega_state g` (which is the main
 * CPU's RAM).
 *
 * Verification: tests/probe_sndboard.c byte-diffs the AY register-write
 * stream of every command against the real ROM running on the Z80
 * (`frametime --sndboard-trace`).
 */
#include <stdint.h>
#include <string.h>
#include "ay8910.h"
#include "platform/omega_platform.h"

/* ROM 0x024A-0x07FF: command table + scripts (omega_sndrom.c) */
extern const uint8_t omega_sndrom[0x05B6];

#define SNDROM_BASE   0x024A
#define SNDROM_END    0x0800
#define SNDRAM_BASE   0x1000
#define SNDRAM_LEN    0x0400

/* RAM symbols, omega_sound.asm.  iy is 0x1000 throughout. */
#define SND_TICK      0x1000    /* (iy+0) NMI counter                     */
#define SND_TICK_PREV 0x1001    /* (iy+1) last value the main loop saw    */
#define SND_SLOT_IDX  0x1002    /* (iy+2) slot being scanned              */
#define SND_CUR_CMD   0x1003    /* (iy+3) running slot, 0x18 = none       */
#define AY_SHADOW     0x1010    /* 32 bytes: AY1 regs 0-15, AY2 regs 0-15 */
#define AY_MIRROR     0x1030    /* 32 bytes: what the chips last received */
#define SCRIPT_SLOTS  0x11C0    /* 23 x {script pc, var ptr}              */
#define CMD_TABLE     0x024A    /* ROM: 23 x {script ptr, var ptr}        */

#define AY_CLOCK_HZ   1000000   /* 12 MHz / 12                            */

/* 244.140625 Hz = 12 MHz / 49152, kept as the exact ratio so the sample
 * count per tick is an integer accumulator, never a rounded float.      */
#define NMI_XTAL_HZ   12000000u
#define NMI_DIVIDER   49152u    /* 16 * 256 * 12                          */

static uint8_t  ram[SNDRAM_LEN];
static ay8910   ay[2];
static int      audio_rate;               /* 0 = register stream only     */
static uint32_t audio_phase;              /* sample fraction, in XTAL Hz  */
static int16_t  audio_buf[2][512];        /* mixer.c's STREAM_BLOCK cap   */

/* 1 = omega_hw_sound() routes commands here instead of to the samples.  */
int omega_sound_ay = 0;

/* Test seam: every AY data write, chip 0/1.  NULL in the game.          */
void (*sndboard_write_hook)(int chip, uint8_t reg, uint8_t val) = 0;

static uint8_t rd(uint16_t a)
{
    if (a >= SNDROM_BASE && a < SNDROM_END)
        return omega_sndrom[a - SNDROM_BASE];
    if (a >= SNDRAM_BASE && a < SNDRAM_BASE + SNDRAM_LEN)
        return ram[a - SNDRAM_BASE];
    return 0xff;        /* open bus. (0x0000-0x0249 is the Z80 program,
                           which no script or pointer ever addresses.)   */
}

static void wr(uint16_t a, uint8_t v)
{
    if (a >= SNDRAM_BASE && a < SNDRAM_BASE + SNDRAM_LEN)
        ram[a - SNDRAM_BASE] = v;
}

static uint16_t rd16(uint16_t a)
{
    return (uint16_t)(rd(a) | (rd((uint16_t)(a + 1)) << 8));
}

/* out ($01),a / out ($03),a with the address latched by the out before */
static void ay_out(int chip, uint8_t reg, uint8_t val)
{
    if (sndboard_write_hook) sndboard_write_hook(chip, reg, val);
    ay8910_write_reg(&ay[chip], reg, val);
}

/* SND_RESET 0x0000 + SND_MAIN 0x0087: clear all RAM, poison the mirror so
 * the next pass rewrites every register, mark all 23 slots dead, then
 * close both mixers in the shadow.  Entered at power-on and by command 0
 * (SND_IRQ_LATCH jumps here without a reti). */
static void snd_reset(void)
{
    memset(ram, 0x00, sizeof ram);                  /* 0x1000-0x13FF      */
    memset(&ram[AY_MIRROR - SNDRAM_BASE], 0xff, 32);
    memset(&ram[SCRIPT_SLOTS - SNDRAM_BASE], 0xff, 0x5c);   /* 23 * 4     */
    wr(AY_SHADOW + 7,  0x3f);                       /* (iy+23) AY1 mixer  */
    wr(AY_SHADOW + 23, 0x3f);                       /* (iy+39) AY2 mixer  */
}

/* 0x004C-0x0064 + irq_var_clear 0x007C, and op_f4_start 0x01F3-0x0213:
 * the ROM has this sequence twice.  Copy command n's 4 table bytes into
 * its slot - the script pointer's clear bit 7 is what makes the slot
 * live - and zero the first two of its variables (delay, loop depth).
 * `sla c` is an 8-bit shift, kept. */
static void slot_start(uint8_t n)
{
    uint16_t bc   = (uint8_t)(n << 1);
    uint16_t slot = (uint16_t)(SCRIPT_SLOTS + bc + bc);
    uint16_t tab  = (uint16_t)(CMD_TABLE + bc + bc);
    uint16_t vars;
    int i;

    for (i = 0; i < 4; i++)
        wr((uint16_t)(slot + i), rd((uint16_t)(tab + i)));
    vars = rd16((uint16_t)(tab + 2));
    wr(vars, 0);
    wr((uint16_t)(vars + 1), 0);
}

/* SND_IRQ_LATCH 0x0038: the main CPU wrote port 0x14. */
static void snd_irq_latch(uint8_t latch)
{
    uint8_t a = latch & 0x7f;

    if (a == 0) { snd_reset(); return; }            /* jp SND_RESET       */
    if (a >= 0x17) return;                          /* irq_exit           */
    if (a == rd(SND_CUR_CMD)) return;               /* cp (iy+3)          */
    slot_start(a);
}

/* SCRIPT_RUN 0x00E7: run one live slot until it delays, ends or yields.
 * hl_slot is the address of the slot's script-pc HIGH byte, as in the
 * ROM's scan.  The slot is marked dead (bit 7) for the duration and the
 * pc is written back only if it is STILL dead at the end: an F4 that
 * restarted this very slot mid-run has replaced it with a live pointer,
 * which must survive. */
static void script_run(uint16_t hl_slot)
{
    uint16_t hl, bc, de, ix, vars;
    uint8_t  a, op, e;

    wr(SND_CUR_CMD, rd(SND_SLOT_IDX));
    hl = rd16((uint16_t)(hl_slot - 1));                     /* script pc  */
    wr(hl_slot, (uint8_t)(rd(hl_slot) | 0x80));
    vars = rd16((uint16_t)(hl_slot + 1));

    a = rd(vars);                                   /* 0x00FC: delay      */
    if (a != 0) {
        a--;
        wr(vars, a);
        if (a != 0) goto script_save_pc;
    }

    for (;;) {                                      /* script_op 0x0109   */
        op = rd(hl);

        if (op < 0xf0) {                            /* register op        */
            e  = op & 0x1f;
            ix = (uint16_t)(AY_SHADOW + e);
            hl++;
            switch (op & 0xe0) {
            case 0x00:                              /* op_reg_load 0x0139 */
                wr(ix, rd(hl));
                /* An envelope-shape load always reaches the chip, even
                 * when the value is unchanged: the write is what
                 * retriggers the envelope.  Poison its mirror byte. */
                if ((e & 0x0f) == 0x0d)
                    wr((uint16_t)(ix + 32), 0xff);
                break;
            case 0x20:                              /* op_reg_load16 0x014A */
                wr(ix, rd(hl));
                hl++;
                wr((uint16_t)(ix + 1), rd(hl));
                break;
            case 0x40:                              /* op_reg_or 0x0155   */
                wr(ix, (uint8_t)(rd(hl) | rd(ix)));
                break;
            case 0x60:                              /* op_reg_and 0x015E  */
                wr(ix, (uint8_t)(rd(ix) & rd(hl)));
                break;
            case 0x80:                              /* op_reg_add 0x0167  */
                wr(ix, (uint8_t)(rd(ix) + rd(hl)));
                break;
            case 0xa0: {                            /* op_reg_add16 0x0170 */
                unsigned lo = (unsigned)rd(ix) + rd(hl);
                wr(ix, (uint8_t)lo);
                hl++;
                wr((uint16_t)(ix + 1),
                   (uint8_t)(rd((uint16_t)(ix + 1)) + rd(hl) + (lo >> 8)));
                break;
            }
            default:                                /* 0xC0 / 0xE0: 0x0136
                                                       jp op_end_script_0235
                                                       - yields the tick,
                                                       does NOT end      */
                hl++;
                goto script_save_pc;
            }
            hl++;                                   /* script_next_op     */
            continue;
        }

        hl++;                                       /* script_ctl_op 0x0181 */
        switch (op) {
        case 0xf1:                                  /* op_f1_delay 0x019F */
            wr(vars, rd(hl));
            hl++;                                   /* op_end_script_0235 */
            goto script_save_pc;

        case 0xf2:                                  /* op_f2_loop_push 0x01A4:
                                                       depth++, then entry
                                                       {count, resume hl}
                                                       at vars+2+4*(depth-1) */
            bc = (uint16_t)(vars + 1);
            a = (uint8_t)(rd(bc) + 1);
            wr(bc, a);
            bc++;
            while (--a != 0) bc += 4;
            wr(bc, rd(hl));
            hl++;
            wr((uint16_t)(bc + 1), rd(hl));
            wr((uint16_t)(bc + 2), (uint8_t)hl);
            wr((uint16_t)(bc + 3), (uint8_t)(hl >> 8));
            break;

        case 0xf3:                                  /* op_f3_loop_end 0x01C3 */
            bc = (uint16_t)(vars + 1);
            a = rd(bc);
            bc++;
            while (--a != 0) bc += 4;
            de = (uint16_t)(rd16(bc) - 1);
            wr((uint16_t)(bc + 1), (uint8_t)(de >> 8));
            wr(bc, (uint8_t)de);
            if (de != 0) {
                hl = rd16((uint16_t)(bc + 2));      /* back to the body   */
            } else {                                /* 0x01E9: pop a level */
                hl--;
                wr((uint16_t)(vars + 1), (uint8_t)(rd((uint16_t)(vars + 1)) - 1));
            }
            break;

        case 0xf4:                                  /* op_f4_start 0x01F3 */
            slot_start(rd(hl));
            break;

        case 0xf5:                                  /* op_f5_kill 0x0219  */
            e  = (uint8_t)(rd(hl) << 1);
            de = (uint16_t)(SCRIPT_SLOTS + 1 + e + e);
            wr(de, (uint8_t)(rd(de) | 0x80));
            break;

        case 0xf6:                                  /* op_f6_jump 0x022A:
                                                       relative to the
                                                       operand's high byte */
            de = rd(hl);
            hl++;
            de |= (uint16_t)(rd(hl) << 8);
            hl = (uint16_t)(hl + de);
            break;

        default:                                    /* op_end_script 0x0231:
                                                       F0, F7-FF          */
            hl |= 0x8000;
            hl++;
            goto script_save_pc;
        }
        hl++;                                       /* script_next_op     */
    }

script_save_pc:                                     /* 0x0236             */
    if (rd(hl_slot) & 0x80) {
        wr(hl_slot, (uint8_t)(hl >> 8));
        wr((uint16_t)(hl_slot - 1), (uint8_t)hl);
    }
    wr(SND_CUR_CMD, 0x18);
}

/* snd_main_loop 0x0090, the body that runs once snd_tick has moved: scan
 * the 23 slots, then snd_ay_flush 0x00BE - send every shadow byte that
 * differs from the mirror. */
static void snd_main_pass(void)
{
    uint16_t hl = SCRIPT_SLOTS + 1;
    int b, c;

    wr(SND_CUR_CMD, 0x18);
    wr(SND_SLOT_IDX, 0);
    for (b = 0x17; b != 0; b--) {                   /* snd_slot_scan      */
        if (!(rd(hl) & 0x80))
            script_run(hl);
        hl += 4;
        wr(SND_SLOT_IDX, (uint8_t)(rd(SND_SLOT_IDX) + 1));
    }

    for (c = 0; c < 0x20; c++) {                    /* snd_ay_flush       */
        uint8_t a = rd((uint16_t)(AY_SHADOW + c));
        if (a == rd((uint16_t)(AY_MIRROR + c))) continue;
        wr((uint16_t)(AY_MIRROR + c), a);
        ay_out(c >> 4, (uint8_t)(c & 0x0f), a);     /* c<16: ports 0/1,
                                                       else ports 2/3    */
    }
}

/* ------------------------------------------------------------------ */
/* host interface                                                      */
/* ------------------------------------------------------------------ */

/* Power-on.  sample_rate 0 = run the board without rendering audio (the
 * probes: the register stream is the product). */
void sndboard_init(int sample_rate)
{
    audio_rate  = sample_rate;
    audio_phase = 0;
    ay8910_init(&ay[0], AY_CLOCK_HZ, sample_rate > 0 ? sample_rate : 48000);
    ay8910_init(&ay[1], AY_CLOCK_HZ, sample_rate > 0 ? sample_rate : 48000);
    snd_reset();
}

/* The main CPU's `out ($14),a`. */
void sndboard_command(uint8_t cmd)
{
    snd_irq_latch(cmd);
}

/* One GBNMI.  SND_NMI_244HZ 0x0066 bumps snd_tick, the main loop sees it
 * move and runs a pass; then the tick's worth of audio is rendered from
 * the registers as that pass left them and pushed to the backend.  The
 * two chips are summed in equal parts (MAME routes both at the same
 * gain); each chip's table tops out at a third of full scale per channel
 * (ay8910.c), so the halved sum cannot clip. */
void sndboard_tick(void)
{
    int n, i;

    wr(SND_TICK, (uint8_t)(rd(SND_TICK) + 1));      /* SND_NMI_244HZ      */
    if (rd(SND_TICK) != rd(SND_TICK_PREV)) {        /* snd_main_loop      */
        wr(SND_TICK_PREV, rd(SND_TICK));
        snd_main_pass();
    }

    if (audio_rate <= 0) return;
    {
        uint64_t acc = (uint64_t)audio_phase + (uint64_t)audio_rate * NMI_DIVIDER;
        n = (int)(acc / NMI_XTAL_HZ);
        audio_phase = (uint32_t)(acc % NMI_XTAL_HZ);
    }
    if (n > (int)(sizeof audio_buf[0] / sizeof audio_buf[0][0]))
        n = (int)(sizeof audio_buf[0] / sizeof audio_buf[0][0]);
    if (n <= 0) return;

    ay8910_render(&ay[0], audio_buf[0], n);
    ay8910_render(&ay[1], audio_buf[1], n);
    for (i = 0; i < n; i++)
        audio_buf[0][i] = (int16_t)(((int)audio_buf[0][i] + (int)audio_buf[1][i]) / 2);
    plat_audio_push(audio_buf[0], n);
}
